[package]
name = "nnshogi"
version = "0.3.0"
authors = ["jinpu"]
[dependencies.usiagent]
#git = "https://github.com/j6k1/USIAgent.git"
path = "../USIAgent"
[dependencies.simplenn]
#git = "https://github.com/j6k1/simplenn.git"
path = "../simplenn"
[dependencies.csaparser]
#git = "https://github.com/j6k1/CsaParser.git"
path = "../CsaParser"
[dependencies]
rand = "0.5"
rand_xorshift = "0.1.1"
statrs = "0.10.0"
getopts = "0.2"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"