[package]
name = "nnshogi"
version = "0.7.0"
authors = ["jinpu"]
[dependencies.usiagent]
#git = "https://github.com/j6k1/USIAgent.git"
path = "../USIAgent"
[dependencies.simplenn]
#git = "https://github.com/j6k1/simplenn.git"
path = "../simplenn"
[dependencies.csaparser]
#git = "https://github.com/j6k1/CsaParser.git"
path = "../CsaParser"
[dependencies.packedsfen]
path = "../packedsfen"
[dependencies]
rand = "0.7.0"
rand_core = "0.5.0"
rand_xorshift = "0.2.0"
statrs = "0.13.0"
getopts = "0.2"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"